# Generated by Django 4.2.27 on 2026-01-13 10:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Product',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['created_on']},
        ),
    ]
