# Generated by Django 4.2.27 on 2026-01-13 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_post_product_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='author',
        ),
    ]
