# Generated by Django 4.2.27 on 2026-01-21 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='approved',
        ),
    ]
