# Generated by Django 4.2.27 on 2026-03-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default='Review Title', max_length=120),
        ),
    ]
